import {BarChart3,FileBarChart,Menu,ReceiptText,Settings,Workflow,X} from 'lucide-react';
import {useState} from 'react';
import {NavLink,Outlet} from 'react-router-dom';

export function Layout(){
 const [open,setOpen]=useState(false);const [dismissed,setDismissed]=useState<string>();
 const links=[['/',ReceiptText,'Журнал продаж'],['/analytics',BarChart3,'Аналитика'],['/scenarios',Workflow,'Сценарии']] as const;
 function closeSubmenu(name:string){setDismissed(name);setOpen(false)}
 return <div className="app"><aside className={open?'open':''}><div className="brand"><span>ЖП</span><div>Журнал продаж<small>Управление данными</small></div><button onClick={()=>setOpen(false)}><X/></button></div><nav>{links.map(([to,Icon,label])=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)}><Icon size={19}/>{label}</NavLink>)}
 <div className={`nav-settings nav-reports ${dismissed==='reports'?'submenu-dismissed':''}`} onMouseLeave={()=>setDismissed(undefined)}><NavLink to="/reports/product-sales"><FileBarChart size={19}/>Отчеты</NavLink><div className="settings-menu"><NavLink to="/reports/product-sales" onClick={()=>closeSubmenu('reports')}>Продажи по товарам</NavLink><NavLink to="/reports/product-analytics" onClick={()=>closeSubmenu('reports')}>Товарная аналитика</NavLink><NavLink to="/reports/category-analytics" onClick={()=>closeSubmenu('reports')}>Аналитика категорий</NavLink><NavLink to="/reports/promotion-candidates" onClick={()=>closeSubmenu('reports')}>Кандидаты в акцию</NavLink><NavLink to="/reports/sales-dynamics" onClick={()=>closeSubmenu('reports')}>Динамика продаж</NavLink><NavLink to="/reports/store-analytics" onClick={()=>closeSubmenu('reports')}>Аналитика по магазинам</NavLink></div></div>
 <div className={`nav-settings ${dismissed==='settings'?'submenu-dismissed':''}`} onMouseLeave={()=>setDismissed(undefined)}><NavLink to="/settings/update"><Settings size={19}/>Настройки</NavLink><div className="settings-menu"><NavLink to="/settings/update" onClick={()=>closeSubmenu('settings')}>Обновление</NavLink><NavLink to="/imports" onClick={()=>closeSubmenu('settings')}>Импорт</NavLink><NavLink to="/settings/ftp" onClick={()=>closeSubmenu('settings')}>FTP</NavLink><NavLink to="/settings/smtp" onClick={()=>closeSubmenu('settings')}>SMTP</NavLink></div></div></nav><footer>Production · PostgreSQL</footer></aside><main><header><button className="mobile" onClick={()=>setOpen(true)}><Menu/></button><div><b>Журнал продаж</b><small>Единый реестр и аналитика</small></div></header><Outlet/></main>{open&&<div className="backdrop" onClick={()=>setOpen(false)}/>}</div>
}
