"""initial schema"""
from alembic import op
import sqlalchemy as sa
revision="20260914_01";down_revision=None;branch_labels=None;depends_on=None
def upgrade():
 op.create_table("import_batches",sa.Column("id",sa.BigInteger(),primary_key=True),sa.Column("filename",sa.String(512),nullable=False),sa.Column("stored_path",sa.String(1024)),sa.Column("file_size",sa.BigInteger(),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("uploaded_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("finished_at",sa.DateTime(timezone=True)),sa.Column("period_start",sa.Date()),sa.Column("period_end",sa.Date()),sa.Column("total_rows",sa.Integer(),nullable=False,server_default="0"),sa.Column("processed_rows",sa.Integer(),nullable=False,server_default="0"),sa.Column("added_rows",sa.Integer(),nullable=False,server_default="0"),sa.Column("duplicate_rows",sa.Integer(),nullable=False,server_default="0"),sa.Column("skipped_rows",sa.Integer(),nullable=False,server_default="0"),sa.Column("error_rows",sa.Integer(),nullable=False,server_default="0"),sa.Column("duration_ms",sa.Integer()),sa.Column("error_text",sa.Text()))
 op.create_index("ix_import_batches_status","import_batches",["status"])
 op.create_table("sales",sa.Column("id",sa.BigInteger(),primary_key=True),sa.Column("row_number",sa.Integer()),sa.Column("sale_date",sa.Date(),nullable=False),sa.Column("document_number",sa.String(128),nullable=False),sa.Column("client",sa.String(512)),sa.Column("department",sa.String(512),nullable=False),sa.Column("total_amount",sa.Numeric(18,2),nullable=False),sa.Column("base_amount",sa.Numeric(18,2)),sa.Column("discount_percent",sa.Numeric(8,4)),sa.Column("reason",sa.Text()),sa.Column("author",sa.String(255)),sa.Column("price_type",sa.String(255)),sa.Column("discount_card_percent",sa.Numeric(8,4)),sa.Column("discount_card_number",sa.String(128)),sa.Column("social",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("certificate_amount",sa.Numeric(18,2)),sa.Column("promotion",sa.String(512)),sa.Column("phone",sa.String(64)),sa.Column("original_products_text",sa.Text()),sa.Column("fingerprint",sa.String(64),nullable=False),sa.Column("import_id",sa.BigInteger(),sa.ForeignKey("import_batches.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.UniqueConstraint("fingerprint"))
 for col in ("sale_date","document_number","client","department","author","price_type","discount_card_number","social","promotion","phone","fingerprint","import_id"):op.create_index(f"ix_sales_{col}","sales",[col])
 op.create_table("sale_items",sa.Column("id",sa.BigInteger(),primary_key=True),sa.Column("sale_id",sa.BigInteger(),sa.ForeignKey("sales.id",ondelete="CASCADE"),nullable=False),sa.Column("article",sa.String(255)),sa.Column("code",sa.String(255)),sa.Column("name",sa.String(1024),nullable=False),sa.Column("quantity",sa.Numeric(18,3),nullable=False),sa.Column("base_price",sa.Numeric(18,2)),sa.Column("actual_price",sa.Numeric(18,2)),sa.Column("extra_data",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
 for col in ("sale_id","article","code","name"):op.create_index(f"ix_sale_items_{col}","sale_items",[col])
 op.create_table("import_errors",sa.Column("id",sa.BigInteger(),primary_key=True),sa.Column("import_id",sa.BigInteger(),sa.ForeignKey("import_batches.id",ondelete="CASCADE"),nullable=False),sa.Column("row_number",sa.Integer()),sa.Column("message",sa.Text(),nullable=False),sa.Column("raw_data",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
 op.create_index("ix_import_errors_import_id","import_errors",["import_id"])
def downgrade():
 op.drop_table("import_errors");op.drop_table("sale_items");op.drop_table("sales");op.drop_table("import_batches")
