import {useMemo,useState} from 'react';
import {Bar,BarChart,CartesianGrid,Cell,Legend,Line,LineChart,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {API,query} from '../api/client';
import {MultiSelect} from '../components/MultiSelect';
import {Empty,ErrorBox,Loading} from '../components/States';
import {useApi} from '../hooks/useApi';
import {date,money,number,percent} from '../utils/format';

type PeriodKind='today'|'yesterday'|'current_week'|'previous_week'|'current_month'|'previous_month'|'custom';
type Comparison={current:number;previous:number;difference:number;change_percent:number|null};
type CategoryRow={category:string;current_revenue:number;previous_revenue:number;current_units:number;current_checks:number;current_average_check:number;current_share:number;previous_share:number;share_change_pp:number;revenue_change:number;revenue_change_percent:number|null;contribution_percent:number|null;contribution:string};
type Report={period:{start:string;end:string};previous_period:{start:string;end:string};warning?:string;metrics:Record<string,Comparison>;categories:CategoryRow[];category_options:string[];structure:Array<{category:string;revenue:number;share:number}>;growth_drivers:CategoryRow[];decline_drivers:CategoryRow[]};
type Detail={category:CategoryRow;products:Array<{article?:string;code?:string;name:string;revenue:number;units:number;checks:number;share:number;revenue_change:number}>;group_by:string;points:Array<{period:string;revenue:number;units:number}>};
const COLORS=['#2878ff','#9b6cff','#22a06b','#f59e0b','#e05263','#25a9c8','#6f7b90','#ef7d32','#58a55c','#b05cc7','#aab3c2'];
const iso=(value:Date)=>`${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,'0')}-${String(value.getDate()).padStart(2,'0')}`;
function periodDates(kind:PeriodKind){const now=new Date(),from=new Date(now),to=new Date(now),day=(now.getDay()+6)%7;if(kind==='yesterday'){from.setDate(from.getDate()-1);to.setDate(to.getDate()-1)}if(kind==='current_week')from.setDate(from.getDate()-day);if(kind==='previous_week'){from.setDate(from.getDate()-day-7);to.setDate(from.getDate()+6)}if(kind==='current_month')from.setDate(1);if(kind==='previous_month'){from.setMonth(from.getMonth()-1,1);to.setDate(0)}return {from:iso(from),to:iso(to)}}
const periods:Array<[PeriodKind,string]>=[['today','Сегодня'],['yesterday','Вчера'],['current_week','Текущая неделя'],['previous_week','Предыдущая неделя'],['current_month','Текущий месяц'],['previous_month','Предыдущий месяц'],['custom','Произвольный период']];
const metricNames:Record<string,string>={revenue:'Выручка',units:'Продано товаров',checks:'Количество чеков',average_check:'Средний чек',categories:'Количество категорий'};
const formatMetric=(key:string,value:number)=>key==='revenue'||key==='average_check'?money(value):number(value);
const signedPercent=(value:number|null)=>value==null?'—':`${value>0?'+':''}${percent(value)}`;
const Memo=({title,children}:{title:string;children:string})=><div className="category-memo"><b>{title}</b><span>{children}</span></div>;

export function CategoryAnalyticsReportPage(){
 const initial=periodDates('current_month');const [kind,setKind]=useState<PeriodKind>('current_month'),[from,setFrom]=useState(initial.from),[to,setTo]=useState(initial.to),[stores,setStores]=useState<string[]>([]),[manager,setManager]=useState(''),[buyerType,setBuyerType]=useState(''),[category,setCategory]=useState(''),[chartLimit,setChartLimit]=useState('10'),[selected,setSelected]=useState<string>(),[detailGroup,setDetailGroup]=useState('');
 const {data:filters}=useApi<{departments:string[]}>('/filters'),{data:managers}=useApi<string[]>('/integrations/clients-vr/managers'),{data:buyerTypes}=useApi<string[]>('/integrations/clients-vr/buyer-types');
 const params={date_from:from,date_to:to,period_kind:kind,stores,manager,buyer_type:buyerType,category};const {data,loading,error}=useApi<Report>(`/reports/category-analytics?${query(params)}`);
 const detailParams=query({...params,category:undefined,group_by:detailGroup||undefined});const {data:detail,loading:detailLoading}=useApi<Detail>(selected?`/reports/category-analytics/${encodeURIComponent(selected)}/details?${detailParams}`:'');
 const compared=useMemo(()=>{const rows=data?.categories||[];return chartLimit==='all'?rows:rows.slice(0,Number(chartLimit))},[data,chartLimit]);
 function selectPeriod(value:PeriodKind){setKind(value);if(value!=='custom'){const range=periodDates(value);setFrom(range.from);setTo(range.to)}}
 async function exportExcel(){const response=await fetch(`${API}/reports/category-analytics/export/xlsx?${query(params)}`);if(!response.ok)return alert('Не удалось сформировать Excel');const url=URL.createObjectURL(await response.blob()),link=document.createElement('a');link.href=url;link.download='category-analytics.xlsx';link.click();URL.revokeObjectURL(url)}
 return <div className="page category-report"><div className="page-title"><div><h1>Аналитика категорий</h1><p>Структура продаж и вклад товарных групп в изменение выручки</p></div><button className="primary" onClick={exportExcel}>Выгрузить в Excel</button></div>
 <section className="panel dynamics-filters"><div className="period-picker">{periods.map(([value,label])=><button key={value} className={kind===value?'active':''} onClick={()=>selectPeriod(value)}>{label}</button>)}</div>{kind==='custom'&&<div className="custom-dates"><label>Дата с<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>Дата по<input type="date" min={from} value={to} onChange={event=>setTo(event.target.value)}/></label></div>}<div className="report-filters"><label>Магазин<MultiSelect options={filters?.departments||[]} value={stores} onChange={setStores} placeholder="Все магазины"/></label><label>Менеджер<select value={manager} onChange={event=>setManager(event.target.value)}><option value="">Все менеджеры</option>{managers?.map(value=><option key={value}>{value}</option>)}</select></label><label>Вид покупателя<select value={buyerType} onChange={event=>setBuyerType(event.target.value)}><option value="">Все виды покупателей</option><option value="Нет">Нет</option>{buyerTypes?.filter(value=>value.toLocaleLowerCase('ru')!=='нет').map(value=><option key={value}>{value}</option>)}</select></label><label>Категория<select value={category} onChange={event=>setCategory(event.target.value)}><option value="">Все категории</option>{data?.category_options.map(value=><option key={value}>{value}</option>)}</select></label></div><Memo title="Как настроить выборку">Период задаёт границы анализа, а магазин, менеджер и вид покупателя позволяют проверить структуру продаж отдельного сегмента. Фильтр категории полезен для углублённого анализа одной товарной группы.</Memo></section>
 {data?.warning&&<div className="report-warning">{data.warning}</div>}{loading?<Loading/>:error?<ErrorBox text={error}/>:!data?null:!data.categories.length?<Empty text="За выбранный период категории не найдены"/>:<><Memo title="Основные показатели">Карточки дают быстрый итог по выбранной выборке. Сравнивайте выручку со средним чеком и числом чеков: так можно понять, вызвано изменение потоком покупателей или стоимостью их покупок.</Memo><div className="kpis category-kpis">{Object.entries(metricNames).map(([key,label])=>{const metric=data.metrics[key];return <div className="kpi" key={key}><span>{label}</span><strong>{formatMetric(key,metric.current)}</strong><small>Прошлый период: {formatMetric(key,metric.previous)}</small><small className={(metric.change_percent||0)>=0?'up':'down'}>{signedPercent(metric.change_percent)}</small></div>})}</div>
 <section className="panel chart category-structure"><h2>Структура выручки по категориям</h2><Memo title="Как читать структуру">Диаграмма показывает, какую часть товарной выручки формирует каждая категория. Крупные сектора — основа оборота; рост зависимости от одной категории повышает риск, а увеличение доли перспективной группы показывает изменение спроса.</Memo><ResponsiveContainer width="100%" height={340}><PieChart><Pie data={data.structure} dataKey="revenue" nameKey="category" innerRadius={62} outerRadius={115} label={({name,percent:part})=>`${name} ${(Number(part)*100).toFixed(1)}%`}>{data.structure.map((_,index)=><Cell key={index} fill={COLORS[index%COLORS.length]}/>)}</Pie><Tooltip formatter={value=>money(Number(value))}/></PieChart></ResponsiveContainer></section>
 <section className="panel chart category-revenue-chart"><div className="section-title"><h2>Выручка по категориям</h2><select value={chartLimit} onChange={event=>setChartLimit(event.target.value)}><option value="10">ТОП-10</option><option value="20">ТОП-20</option><option value="all">Все</option></select></div><Memo title="Сравнение периодов">Вертикальные столбцы сопоставляют текущую и прошлую выручку. Большой разрыв между столбцами сразу показывает лидеров роста и категории, которые требуют проверки ассортимента, наличия или продвижения.</Memo><div className="category-bars"><div style={{width:`max(100%, ${Math.max(compared.length*110,900)}px)`,height:400}}><ResponsiveContainer width="100%" height="100%"><BarChart data={compared} margin={{left:20,right:20,bottom:80}}><CartesianGrid strokeDasharray="3 3"/><XAxis type="category" dataKey="category" angle={-35} textAnchor="end" interval={0} height={95}/><YAxis type="number" width={95} tickFormatter={number}/><Tooltip formatter={value=>money(Number(value))}/><Legend verticalAlign="top"/><Bar dataKey="current_revenue" name="Текущий период" fill="#2878ff"/><Bar dataKey="previous_revenue" name="Предыдущий период" fill="#9b6cff"/></BarChart></ResponsiveContainer></div></div></section>
 <div className="category-drivers"><section className="panel driver-card"><h2>Что обеспечило рост</h2><Memo title="Драйверы роста">Здесь категории с максимальным приростом в рублях. Они показывают, какие товарные группы реально обеспечили улучшение общего результата и где стоит поддержать наличие и продвижение.</Memo>{data.growth_drivers.length?data.growth_drivers.map(row=><button key={row.category} onClick={()=>setSelected(row.category)}><span>{row.category}</span><b className="trend-up">+{money(row.revenue_change)}</b></button>):<p className="muted">Категорий с ростом за выбранный период нет</p>}</section><section className="panel driver-card"><h2>Категории с падением</h2><Memo title="Зоны внимания">Блок ранжирует отрицательный вклад по сумме потери. Верхние позиции сильнее всего тянут выручку вниз — для них полезно проверить остатки, цены, сезонность и изменение спроса.</Memo>{data.decline_drivers.length?data.decline_drivers.map(row=><button key={row.category} onClick={()=>setSelected(row.category)}><span>{row.category}</span><b className="trend-down">{money(row.revenue_change)}</b></button>):<p className="muted">Категорий со снижением продаж за выбранный период нет</p>}</section></div>
 <section className="panel table-panel"><div className="section-title"><div><h2>Категории</h2><p>{date(data.period.start)} — {date(data.period.end)} · сравнение с {date(data.previous_period.start)} — {date(data.previous_period.end)}</p></div></div><Memo title="Подробная аналитика">Таблица объединяет объём, долю, средний чек и вклад в изменение выручки. Рост доли при падении общей выручки не всегда означает рост категории, поэтому оценивайте долю вместе с абсолютным изменением. Нажмите строку для просмотра товаров и динамики.</Memo><div className="table-wrap category-table"><table><thead><tr><th>Категория</th><th>Выручка</th><th>Доля</th><th>Продано</th><th>Чеков</th><th>Средний чек</th><th>Прошлая выручка</th><th>Изменение, ₽</th><th>Изменение, %</th><th>Доля, п.п.</th><th>Вклад, %</th></tr></thead><tbody>{data.categories.map(row=><tr key={row.category} onClick={()=>setSelected(row.category)}><td><b>{row.category}</b></td><td>{money(row.current_revenue)}</td><td>{percent(row.current_share)}</td><td>{number(row.current_units)}</td><td>{number(row.current_checks)}</td><td>{money(row.current_average_check)}</td><td>{money(row.previous_revenue)}</td><td className={row.revenue_change>=0?'trend-up':'trend-down'}>{money(row.revenue_change)}</td><td>{signedPercent(row.revenue_change_percent)}</td><td>{row.share_change_pp>0?'+':''}{percent(row.share_change_pp)}</td><td>{signedPercent(row.contribution_percent)}</td></tr>)}</tbody></table></div></section></>}
 {selected&&<><div className="backdrop" onClick={()=>setSelected(undefined)}/><section className="category-detail"><div className="drawer-head"><div><small>Детализация категории</small><h2>{selected}</h2></div><button onClick={()=>setSelected(undefined)}>Закрыть</button></div><div className="drawer-body">{detailLoading?<Loading/>:detail&&<><Memo title="Показатели категории">Сводка помогает оценить масштаб категории и её изменение. Сопоставляйте долю, число чеков и средний чек, чтобы понять, зависит результат от охвата покупателей или суммы товаров категории в чеке.</Memo><div className="kpis category-detail-kpis">{[['Выручка',money(detail.category.current_revenue)],['Продано',number(detail.category.current_units)],['Чеков',number(detail.category.current_checks)],['Средний чек',money(detail.category.current_average_check)],['Доля',percent(detail.category.current_share)],['Изменение',money(detail.category.revenue_change)]].map(([label,value])=><div className="kpi" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><section className="panel chart"><div className="section-title"><h2>Динамика выручки</h2><div className="chart-granularity">{['day','week','month'].map(value=><button key={value} className={(detailGroup||detail.group_by)===value?'active':''} onClick={()=>setDetailGroup(value)}>{value==='day'?'По дням':value==='week'?'По неделям':'По месяцам'}</button>)}</div></div><Memo title="Динамика категории">График показывает устойчивость продаж во времени. Провалы помогают найти дни или недели потери спроса, а длительный рост отличить от разовой крупной продажи.</Memo><ResponsiveContainer width="100%" height={300}><LineChart data={detail.points}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="period" tickFormatter={date}/><YAxis width={95} tickFormatter={number}/><Tooltip formatter={value=>money(Number(value))}/><Line dataKey="revenue" name="Выручка" stroke="#2878ff" strokeWidth={3}/></LineChart></ResponsiveContainer></section><h3>ТОП товаров категории</h3><Memo title="Товары внутри категории">Таблица показывает, какие позиции формируют результат категории. Высокая доля одного товара означает зависимость от его наличия; отрицательное изменение помогает найти конкретные источники падения.</Memo><div className="table-wrap"><table><thead><tr><th>Артикул</th><th>Код</th><th>Наименование</th><th>Выручка</th><th>Продано</th><th>Чеков</th><th>Доля</th><th>Изменение</th></tr></thead><tbody>{detail.products.map((row,index)=><tr key={`${row.code}-${row.article}-${index}`}><td>{row.article||'—'}</td><td>{row.code||'—'}</td><td>{row.name}</td><td>{money(row.revenue)}</td><td>{number(row.units)}</td><td>{number(row.checks)}</td><td>{percent(row.share)}</td><td className={row.revenue_change>=0?'trend-up':'trend-down'}>{money(row.revenue_change)}</td></tr>)}</tbody></table></div></>}</div></section></>}</div>;
}
