import {History,Play,Save,Server,X} from 'lucide-react';
import {useEffect,useState} from 'react';
import {api} from '../api/client';

type Form={protocol:string;host:string;port:number;username:string;password:string;directory:string;retries:number;retry_delay:number;enabled:boolean;has_password?:boolean};
type AutoLog={id:number;filename?:string;status:string;message?:string;import_id?:number;started_at:string;finished_at?:string};
const empty:Form={protocol:'FTP',host:'',port:21,username:'',password:'',directory:'/',retries:5,retry_delay:3,enabled:true};
export function FtpSettingsPage(){
 const [form,setForm]=useState<Form>(empty);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [history,setHistory]=useState<AutoLog[]>();
 useEffect(()=>{api<Form>('/ftp/settings').then(data=>setForm({...data,password:''})).catch(error=>setMessage(error.message))},[]);
 async function action(kind:'save'|'test'){setBusy(true);setMessage('');try{if(kind==='save'){const data=await api<Form>('/ftp/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});setForm({...data,password:''});setMessage('Настройки FTP сохранены')}else{const result=await api<{files:number}>('/ftp/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});setMessage(`Подключение установлено. Файлов в каталоге: ${result.files}`)}}catch(error){setMessage(error instanceof Error?error.message:'Ошибка FTP')}finally{setBusy(false)}}
 async function openHistory(){setHistory(await api<AutoLog[]>('/ftp/history'))}
 async function runNow(){setBusy(true);try{await api('/ftp/run',{method:'POST'});setMessage('Автозагрузка запущена. Результат появится в истории.')}catch(error){setMessage(error instanceof Error?error.message:'Ошибка автозагрузки')}finally{setBusy(false)}}
 return <div className="page"><div className="page-title"><div><h1>FTP</h1><p>Ежедневная автозагрузка запускается в 23:55</p></div><button onClick={openHistory}><History size={17}/>История автозагрузок</button></div><section className="panel ftp-panel"><h2>Подключение к FTP для автозагрузки</h2><div className="ftp-form"><label>Протокол<select value={form.protocol} onChange={e=>setForm({...form,protocol:e.target.value})}><option>FTP</option><option>FTPS</option></select></label><label>Хост<input value={form.host} onChange={e=>setForm({...form,host:e.target.value})}/></label><label>Порт<input type="number" value={form.port} onChange={e=>setForm({...form,port:+e.target.value})}/></label><label>Логин<input value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Пароль<input type="password" placeholder={form.has_password?'Оставьте пустым, чтобы не менять':'Введите пароль'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>Каталог с XLS/XLSX<input value={form.directory} onChange={e=>setForm({...form,directory:e.target.value})}/></label><label>Количество попыток подключения<input type="number" min="1" max="20" value={form.retries} onChange={e=>setForm({...form,retries:+e.target.value})}/></label><label>Задержка между попытками, секунд<input type="number" min="0" value={form.retry_delay} onChange={e=>setForm({...form,retry_delay:+e.target.value})}/></label><label className="ftp-enabled"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/>Автозагрузка включена</label></div>{message&&<p className="ftp-message">{message}</p>}<div className="actions"><button className="primary" disabled={busy} onClick={()=>action('save')}><Save size={17}/>Сохранить подключение</button><button disabled={busy} onClick={()=>action('test')}><Server size={17}/>Проверить подключение</button><button disabled={busy} onClick={runNow}><Play size={17}/>Запустить сейчас</button></div></section>{history&&<><div className="backdrop" onClick={()=>setHistory(undefined)}/><div className="history-modal"><div className="period-modal-head"><div><h2>История автозагрузок</h2><p>Последние 200 запусков и файлов</p></div><button onClick={()=>setHistory(undefined)}><X/></button></div><div className="table-wrap"><table><thead><tr><th>Время</th><th>Файл</th><th>Статус</th><th>Результат</th></tr></thead><tbody>{history.map(item=><tr key={item.id}><td>{new Date(item.started_at).toLocaleString('ru-RU')}</td><td>{item.filename||'—'}</td><td><span className={`status ${item.status}`}>{item.status}</span></td><td className="wrap-cell">{item.message||'—'}</td></tr>)}</tbody></table></div></div></>}</div>
}
