import {History,Save,Send,X} from 'lucide-react';
import {useEffect,useState} from 'react';
import {api} from '../api/client';

type Form={host:string;port:number;security:string;username:string;password:string;sender_email:string;sender_name:string;has_password?:boolean};
type HistoryRow={id:number;run_date:string;status:string;message?:string};
const empty:Form={host:'smtp.yandex.ru',port:587,security:'STARTTLS',username:'',password:'',sender_email:'',sender_name:''};

export function SmtpSettingsPage(){
 const [form,setForm]=useState(empty);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [history,setHistory]=useState<HistoryRow[]>();const [testOpen,setTestOpen]=useState(false);const [testEmail,setTestEmail]=useState('');
 useEffect(()=>{api<Form|null>('/smtp/settings').then(value=>value&&setForm({...value,password:''})).catch(error=>setMessage(error.message))},[]);
 async function save(){setBusy(true);try{setForm({...await api<Form>('/smtp/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}),password:''});setMessage('Настройки SMTP сохранены')}catch(error){setMessage(error instanceof Error?error.message:'Ошибка SMTP')}finally{setBusy(false)}}
 async function sendTest(){if(!testEmail.trim()){setMessage('Введите тестовый email');return}setBusy(true);try{await api('/smtp/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:testEmail.trim()})});setMessage(`Тестовое письмо отправлено на ${testEmail.trim()}`);setTestOpen(false);setTestEmail('')}catch(error){setMessage(error instanceof Error?error.message:'Ошибка отправки')}finally{setBusy(false)}}
 return <div className="page"><div className="page-title"><div><h1>SMTP-сервер</h1><p>Параметры отправки отчетов и системных уведомлений</p></div></div><section className="panel smtp-panel"><h2>SMTP-сервер</h2><div className="smtp-form"><label className="wide">SMTP-сервер<input value={form.host} onChange={e=>setForm({...form,host:e.target.value})}/></label><label>Порт<input type="number" value={form.port} onChange={e=>setForm({...form,port:+e.target.value})}/></label><label>Тип защиты<select value={form.security} onChange={e=>setForm({...form,security:e.target.value})}><option>STARTTLS</option><option>SSL</option><option>Нет</option></select></label><label>Логин<input value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Пароль<input type="password" placeholder={form.has_password?'Оставьте пустым, чтобы не менять':'Введите пароль'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>Email отправителя<input type="email" value={form.sender_email} onChange={e=>setForm({...form,sender_email:e.target.value})}/></label><label>Имя отправителя<input value={form.sender_name} onChange={e=>setForm({...form,sender_name:e.target.value})}/></label></div>{message&&<p className="ftp-message">{message}</p>}<div className="actions"><button className="primary" disabled={busy} onClick={save}><Save size={17}/>Сохранить SMTP</button><button disabled={busy} onClick={()=>setTestOpen(true)}><Send size={17}/>Отправить тест</button><button onClick={async()=>setHistory(await api<HistoryRow[]>('/smtp/history'))}><History size={17}/>История уведомлений</button></div></section>
 {testOpen&&<><div className="backdrop" onClick={()=>setTestOpen(false)}/><div className="column-modal" role="dialog" aria-modal="true" aria-labelledby="test-email-title"><div className="period-modal-head"><div><h2 id="test-email-title">Отправить тестовое письмо</h2><p>Укажите адрес получателя для разовой проверки SMTP</p></div><button aria-label="Закрыть" onClick={()=>setTestOpen(false)}><X/></button></div><label>Тестовый email<input autoFocus type="email" placeholder="user@example.ru" value={testEmail} onChange={e=>setTestEmail(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendTest()}/></label><div className="actions"><button className="primary" disabled={busy} onClick={sendTest}><Send size={17}/>{busy?'Отправка…':'Отправить'}</button><button onClick={()=>setTestOpen(false)}>Отмена</button></div></div></>}
 {history&&<><div className="backdrop" onClick={()=>setHistory(undefined)}/><div className="history-modal"><div className="period-modal-head"><h2>История уведомлений</h2><button onClick={()=>setHistory(undefined)}><X/></button></div><div className="table-wrap"><table><thead><tr><th>Дата</th><th>Статус</th><th>Результат</th></tr></thead><tbody>{history.map(row=><tr key={row.id}><td>{new Date(row.run_date).toLocaleDateString('ru-RU')}</td><td>{row.status}</td><td>{row.message||'—'}</td></tr>)}</tbody></table></div></div></>}</div>
}
