import React from 'react';import ReactDOM from 'react-dom/client';import {BrowserRouter,Route,Routes} from 'react-router-dom';import {Layout} from './components/Layout';import {AnalyticsPage} from './pages/AnalyticsPage';import {ImportsPage} from './pages/ImportsPage';import {JournalPage} from './pages/JournalPage';import './styles.css';
import {SettingsPage} from './pages/SettingsPage';
import {FtpSettingsPage} from './pages/FtpSettingsPage';
import {ScenariosPage} from './pages/ScenariosPage';import {SmtpSettingsPage} from './pages/SmtpSettingsPage';
import {ProductSalesReportPage} from './pages/ProductSalesReportPage';
import {HorecaReportPage} from './pages/HorecaReportPage';
import {SalesDynamicsReportPage} from './pages/SalesDynamicsReportPage';
import {StoreAnalyticsReportPage} from './pages/StoreAnalyticsReportPage';
import {ProductAnalyticsPage} from './pages/ProductAnalyticsPage';
import {CategoryAnalyticsReportPage} from './pages/CategoryAnalyticsReportPage';
import {PromotionCandidatesPage} from './pages/PromotionCandidatesPage';
const basename=(import.meta.env.VITE_BASE_PATH||'/vr/sales/').replace(/\/$/,'');ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter basename={basename}><Routes><Route path="/reports/horeca/:token" element={<HorecaReportPage/>}/><Route element={<Layout/>}><Route path="/" element={<JournalPage/>}/><Route path="/analytics" element={<AnalyticsPage/>}/><Route path="/reports/product-sales" element={<ProductSalesReportPage/>}/><Route path="/reports/product-analytics" element={<ProductAnalyticsPage/>}/><Route path="/reports/category-analytics" element={<CategoryAnalyticsReportPage/>}/><Route path="/reports/promotion-candidates" element={<PromotionCandidatesPage/>}/><Route path="/reports/sales-dynamics" element={<SalesDynamicsReportPage/>}/><Route path="/reports/store-analytics" element={<StoreAnalyticsReportPage/>}/><Route path="/scenarios" element={<ScenariosPage/>}/><Route path="/imports" element={<ImportsPage/>}/><Route path="/settings" element={<SettingsPage/>}/><Route path="/settings/update" element={<SettingsPage/>}/><Route path="/settings/ftp" element={<FtpSettingsPage/>}/><Route path="/settings/smtp" element={<SmtpSettingsPage/>}/></Route></Routes></BrowserRouter></React.StrictMode>);
